#!/bin/sh

exec 2>&1

if test -x /usr/share/qmail/create-config-qmail-qmqpd ; then
    test /etc/sysconfig/qmail -nt ./env/ADDRESS -o /etc/sysconfig/mail -nt ./env/ADDRESS && \
	/usr/share/qmail/create-config-qmail-qmqpd
fi

exec envdir ./env sh -c '
    test -s ./rules/data.cdb && tcprules="-x ./rules/data.cdb" || tcprules=""

    exec \
	${LIMIT:+softlimit -m $LIMIT} \
	envuidgid qmaild \
	tcpserver -dRUvX -c ${CONCURRENCY:-20} -l ${LOCALNAME:-$(head -1 /etc/qmail/control/me)} \
		$tcprules ${ADDRESS:-0} ${PORT:-628} \
	qmail-qmqpd
'
