#!/bin/sh

test -x /usr/share/qmail/create-log-config-qmail-pop3d -a /etc/sysconfig/qmail -nt ../env/LOGSIZE && \
    /usr/share/qmail/create-log-config-qmail-pop3d

exec envdir ../env sh -c '
    exec setuidgid qmaillog \
	multilog t ${LOGSIZE+s$LOGSIZE} ${LOGNUM+n$LOGNUM} /var/log/qmail-pop3d
'
