#!/bin/sh

exec envdir /etc/vmailmgr/env sh -c '
    cd /var/log/vmailmgr
    exec \
	setuidgid vmaillog \
	multilog t ${VMAILMGRLOCAL_LOGSIZE+"s$VMAILMGRLOCAL_LOGSIZE"} ${VMAILMGRLOCAL_LOGNUM+"s$VMAILMGRLOCAL_LOGNUM"} \
	./local
'
