#!/bin/sh

exec 2>&1


if test -x /usr/share/cvm/create-config-cvm-vmlookup-local ; then
    test /etc/sysconfig/cvm -nt ./env/SOCKET -o ! -s ./env/CVM_LOOKUP_SECRET && \
	/usr/share/cvm/create-config-cvm-vmlookup-local
fi

exec envdir ./env sh -c '
    exec ${LIMIT:+softlimit -m $LIMIT} \
	cvm-vmailmgr cvm-local:${SOCKET:-/var/run/cvm-vmlookup}
'
