#!/bin/sh

test -x /usr/share/mailfront/create-log-config-mailfront-qmtpd -a /etc/sysconfig/mailfront -nt ../env/LOGSIZE && \
    /usr/share/mailfront/create-log-config-mailfront-qmtpd

exec envdir ../env sh -c '
    exec setuidgid qmaillog \
	multilog t ${LOGSIZE+s$LOGSIZE} ${LOGNUM+n$LOGNUM} /var/log/mailfront-qmtpd
'
