#!/bin/sh

test -x /usr/share/cvm/create-log-config-cvm-qmail-local -a /etc/sysconfig/cvm -nt ../env/LOGSIZE && \
	/usr/share/cvm/create-log-config-cvm-qmail-local

exec envdir ../env sh -c '
    exec setuidgid nobody \
	multilog t ${LOGSIZE+s$LOGSIZE} ${LOGNUM+n$LOGNUM} /var/log/cvm-qmail-local
'
