#!/bin/sh

exec 2>&1

test -x /usr/share/cvm/create-config-cvm-qmail-local -a /etc/sysconfig/cvm -nt ./env/SOCKET && \
	/usr/share/cvm/create-config-cvm-qmail-local

exec envdir ./env sh -c '
    exec ${LIMIT:+softlimit -m $LIMIT} \
	cvm-qmail cvm-local:${SOCKET:-/var/run/cvm-qmail}
'
