#! /bin/sh
#
# Author: Bernhard Graf <graf@movingtarget.de>
#
# /etc/init.d/mailfront-submissiond
#
#   and symbolic its link
#
# /usr/sbin/rcmailfront-submissiond
#
# System startup script for mailfront-submissiond
#
### BEGIN INIT INFO
# Provides:		mailfront-submissiond
# Required-Start:	$network $named $remote_fs qmail
# Required-Stop:	$network $named $remote_fs qmail
# Default-Start:	3 5
# Default-Stop:		0 1 2 6
# Description:		Start mailfront-submissiond
### END INIT INFO

test -L "/service/mailfront-submissiond" || exit 5

# Shell functions sourced from /etc/rc.status
. /etc/rc.status

# First reset status of this service
rc_reset

case "$1" in
    start)
	echo -n "Starting mailfront-submissiond"
	if svc-isdown 2>/dev/null qmail ; then
	  echo -n " ... qmail not running - waiting 1s ..."
	  sleep 1
	  if svc-isdown 2>/dev/null qmail ; then
	    rc_failed 5
            rc_status -v
	    rc_exit
	  fi
	fi
	svc-start mailfront-submissiond

	# Remember status and be verbose
	rc_status -v
	;;
    stop)
	echo -n "Shutting down mailfront-submissiond"
	svc-stop mailfront-submissiond

	# Remember status and be verbose
	rc_status -v
	;;
    try-restart)
	## Stop the service and if this succeeds (i.e. the 
	## service was running before), start it again.
	$0 stop  &&  $0 start

	# Remember status and be quiet
	rc_status
	;;
    restart)
	## Stop the service and regardless of whether it was
	## running or not, start it again.
	$0 stop
	$0 start

	# Remember status and be quiet
	rc_status
	;;
    reload|force-reload)
	## Signal the daemon to reload its config with svc -t .
	echo -n "Reloading mailfront-submissiond"
	## if it supports it:
	svc -t /service/mailfront-submissiond
	svc -t /service/mailfront-submissiond/log

	rc_status -v
	;;
    status)
	echo -n "Checking for mailfront-submissiond: "
	svc-status mailfront-submissiond
	;;
    *)
	echo "Usage: $0 {start|stop|status|try-restart|restart|reload}"
	exit 1
	;;
esac
rc_exit
