#! /bin/sh
#
# Author: Bernhard Graf <graf@movingtarget.de>
#
# /etc/init.d/mailfront-pop3sd
#
#   and symbolic its link
#
# /usr/sbin/rcmailfront-pop3sd
#
# System startup script for mailfront-pop3sd
#
### BEGIN INIT INFO
# Provides:		mailfront-pop3sd
# Required-Start:	$network $remote_fs
# Required-Stop:	$network $remote_fs
# Default-Start:	3 5
# Default-Stop:		0 1 2 6
# Description:		Start mailfront-pop3sd
### END INIT INFO

test -L "/service/mailfront-pop3sd" || exit 5

# Shell functions sourced from /etc/rc.status
. /etc/rc.status

# First reset status of this service
rc_reset

case "$1" in
    start)
	echo -n "Starting mailfront-pop3sd"
	svc-start mailfront-pop3sd

	# Remember status and be verbose
	rc_status -v
	;;
    stop)
	echo -n "Shutting down mailfront-pop3sd"
	svc-stop mailfront-pop3sd

	# Remember status and be verbose
	rc_status -v
	;;
    try-restart)
	## Stop the service and if this succeeds (i.e. the 
	## service was running before), start it again.
	$0 stop  &&  $0 start

	# Remember status and be quiet
	rc_status
	;;
    restart)
	## Stop the service and regardless of whether it was
	## running or not, start it again.
	$0 stop
	$0 start

	# Remember status and be quiet
	rc_status
	;;
    reload|force-reload)
	## Signal the daemon to reload its config with svc -t .
	echo -n "Reloading mailfront-pop3sd"
	## if it supports it:
	svc -t /service/mailfront-pop3sd
	svc -t /service/mailfront-pop3sd/log

	rc_status -v
	;;
    status)
	echo -n "Checking for mailfront-pop3sd: "
	svc-status mailfront-pop3sd
	;;
    *)
	echo "Usage: $0 {start|stop|status|try-restart|restart|reload}"
	exit 1
	;;
esac
rc_exit
