#!/bin/sh

test -x /usr/share/cvm/create-log-config-cvm-vmlookup-local -a /etc/sysconfig/cvm -nt ../env/LOGSIZE && \
	/usr/share/cvm/create-log-config-cvm-vmlookup-local

exec envdir ../env sh -c '
   exec setuidgid nobody \
	multilog t ${LOGSIZE+s$LOGSIZE} ${LOGNUM+n$LOGNUM} /var/log/cvm-vmlookup-local
'
