#!/bin/sh

exec 2>&1

test -x /usr/share/cvm/create-config-cvm-qmail-udp -a /etc/sysconfig/cvm -nt ./env/ADDRESS && \
	/usr/share/cvm/create-config-cvm-qmail-udp

exec envdir ./env sh -c '
    exec ${LIMIT:+softlimit -m $LIMIT} \
	cvm-qmail cvm-udp:${ADDRESS:-0}:{PORT:-325}
'
