#! /bin/sh
#
# Author: Bernhard Graf <graf@movingtarget.de>
#
# /etc/init.d/vmailmgrd-local
#
#   and symbolic its link
#
# /usr/sbin/rcvmailmgrd-local
#
# System startup script for vmailmgrd-local
#
### BEGIN INIT INFO
# Provides:		vmailmgrd-local
# Required-Start:	$remote_fs qmail
# Required-Stop:	$remote_fs qmail
# Default-Start:	3 5
# Default-Stop:		0 1 2 6
# Description:		Start vmailmgrd-local
### END INIT INFO

test -L "/service/vmailmgrd-local" || exit 5

# Shell functions sourced from /etc/rc.status
. /etc/rc.status

# First reset status of this service
rc_reset

case "$1" in
    start)
	echo -n "Starting vmailmgrd-local"
	svc-start vmailmgrd-local

	# Remember status and be verbose
	rc_status -v
	;;
    stop)
	echo -n "Shutting down vmailmgrd-local"
	svc-stop vmailmgrd-local

	# Remember status and be verbose
	rc_status -v
	;;
    try-restart)
	## Stop the service and if this succeeds (i.e. the 
	## service was running before), start it again.
	$0 stop  &&  $0 start

	# Remember status and be quiet
	rc_status
	;;
    restart)
	## Stop the service and regardless of whether it was
	## running or not, start it again.
	$0 stop
	$0 start

	# Remember status and be quiet
	rc_status
	;;
    reload|force-reload)
	## Signal the daemon to reload its config with svc -t .
	echo -n "Reloading vmailmgrd-local"
	## if it supports it:
	svc -t "/service/vmailmgrd-local"

	rc_status -v
	;;
    status)
	echo -n "Checking for vmailmgrd-local: "
	svc-status vmailmgrd-local
	;;
    *)
	echo "Usage: $0 {start|stop|status|try-restart|restart|reload}"
	exit 1
	;;
esac
rc_exit
